// <auto-generated />
namespace FYPMustafa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RestuarantIDincategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestuarantIDincategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201812081845512_RestuarantID in categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
