// <auto-generated />
namespace FYPMustafa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tableandquantitytoorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tableandquantitytoorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201901151347172_table and quantity to order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
